name = "ITensorsITensorBaseCompat"
uuid = "06001d2b-06b1-4bfe-9828-8c6ae543e18d"
version = "0.2.1"
authors = ["ITensor developers <support@itensor.org> and contributors"]

[workspace]
projects = ["benchmark", "dev", "docs", "examples", "test"]

[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
BackendSelection = "680c2d7c-f67a-4cc9-ae9c-da132b1447a5"
ITensorBase = "4795dd04-0d67-49bb-8f44-b89c448a1dc7"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MatrixAlgebraKit = "6c742aac-3347-4629-af66-fc926824e5e4"
TensorAlgebra = "68bd88dc-f39d-4e12-b2ca-f046b68fcc6a"

[compat]
Adapt = "4"
BackendSelection = "0.1"
ITensorBase = "0.10.9, 0.13"
LinearAlgebra = "1"
MatrixAlgebraKit = "0.6"
TensorAlgebra = "0.17"
julia = "1.10"
